version: "3.7"

services:
  safari_app:
    container_name: safari_push_notifications_app_container
    build:
      context: ".."
      dockerfile: "docker/source/Dockerfile"
    volumes:
      - "app_code:/app"
  safari_php:
    container_name: safari_push_notifications_php_container
    build:
      context: ./php
    hostname: "app-php"
    depends_on:
      - safari_app
    volumes:
      - "app_code:/app"
    environment:
      CertficatePath: "CertificatesStaging.p12"
      CertficatePassword: "password"
  nginx:
    container_name: safari_push_notifications_nginx_container
    build:
      context: ./nginx
    hostname: "my-nginx"
    depends_on:
      - safari_php
    volumes:
      - "app_code:/app"
    ports:
      - 5015:80
    environment:
      CertficatePath: "CertificatesStaging.p12"
      CertficatePassword: "password"
volumes:
  app_code:
    name: "app_code_volume"
